services:
  api-rest-cliente-transbank:
    build: ./api-rest-cliente-transbank
    ports:
      - "8900:8900"
    #environment:
    #  - APP_DIRECTORY api-rest-cliente-transbank
    volumes:
      - ./api-rest-cliente-transbank/:/opt/app/api-rest-cliente-transbank
    networks:
      - transbank-net      

  portal-flask-web:
    build: ./portal_flask_web
    ports:
      - "9000:9000"
    volumes:
      - ./portal_flask_web/:/opt/app/portal_flask_web
    environment:
     - API_REST_HOST=api-rest-cliente-transbank
     - API_REST_PORT=8900
    networks:
      - transbank-net

  portal-web:
    build: ./portal-web
    ports:
      - "9100:80"
    volumes:
      - ./portal-web/:/var/www/localhost/htdocs/portal-web
    networks:
      - transbank-net      

networks:
  transbank-net: